name: branch
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.2.0
  translator: ^0.1.7
  screenshot: ^1.2.3
  share_plus: ^2.1.4
  path_provider: ^2.0.2
  http: ^0.13.0+4
  flutter_colorpicker: ^1.0.3
  connectivity_plus: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/bg_1.png
